import * as THREE from 'three';
import { RoomEnvironment } from 'three/addons/environments/RoomEnvironment.js';
import { World } from './world.js';
import { Soundscape } from './audio.js';
import { initialRun, safeSave, interact, moveCircle, actionsForKeys, SAVE_KEY, ROOM_IDS, TRACE_IDS, traceCount, QUIET_SECONDS, WALK_SPEED, RUN_SPEED } from './rules.js';
import story from './story.json';

const ROOM_NAMES={office:'Your room',hub:'Department of Almost',approval:'Office of Permission',button:'The smallest possible favor',loop:'A short corridor',archive:'Archive of lives not lived',gallery:'The museum of you',observatory:'The unwritten sky',garden:'Somewhere unmeasured',quiet:'A room without a task',records:'Records of Nearly',mirror:'A room of you',stairwell:'The stairs that arrive',workshop:'Where the Building is mended',flood:'The floor that remembers',rooftop:'Above the Building'};
const ENDINGS_TOTAL=12;
const TRACES={file:['The file','A page on your desk, and a folder in Records, both carrying your name and dated before you arrived.'],photograph:['The photograph','A lobby flyer asking HAVE YOU SEEN THIS PERSON? The picture has been removed, as though the department decided mid-sentence.'],recording:['The recording','A voice under the water, four words long, still running after nine hundred years.'],handprint:['The handprint','A grip pressed into wood, once in Records and again under the workshop panel. The same hand, twice.'],name:['The name','Two names carved where the building meets the sky. Both of them yours. One of them unfinished.' ]};
const $=id=>document.getElementById(id);
const show=(id,value=true)=>{$(id).hidden=!value;};
const overlays=['menu','pause','settings','ending','collection','transcript','dossier'];
function readStorage(key,fallback) {try{return JSON.parse(localStorage.getItem(key))??fallback;}catch{return fallback;}}

class Game {
 constructor(){
  this.qaMode=new URLSearchParams(location.search).get('qa')==='1';this.state='menu';this.run=initialRun();this.saved=this.qaMode?safeSave(null):safeSave(readStorage(SAVE_KEY,null));this.history=[];this.keys=new Set();this.yaw=0;this.pitch=0;this.dragging=false;this.mouseCaptured=false;this.transitioning=false;this.target=null;this.subtitleUntil=0;this.toastUntil=0;this.idleTime=0;this.idleStage=0;this.stepClock=0;this.lastInteract=0;this.fps=60;this.frameSamples=[];this.lastSave=0;this.startTime=performance.now();this.metrics={frames:0,interactions:0,roomChanges:0,errors:[],maxDraws:0,qualityChanges:0};
  const prefs=readStorage('sadmans-parable:settings',{});this.settings={sensitivity:1,voice:true,muted:false,motion:matchMedia('(prefers-reduced-motion: reduce)').matches,quality:'auto',...prefs};
  this.settings.sensitivity=Math.max(0.4,Math.min(2.4,Number(this.settings.sensitivity)||1));if(!['auto','high','low'].includes(this.settings.quality))this.settings.quality='auto';
  this.audio=new Soundscape();this.audio.voice=!!this.settings.voice;this.audio.mute(this.settings.muted);
  this.renderer=new THREE.WebGLRenderer({canvas:$('world'),antialias:true,alpha:false,powerPreference:'high-performance'});this.renderer.outputColorSpace=THREE.SRGBColorSpace;this.renderer.toneMapping=THREE.ACESFilmicToneMapping;this.renderer.toneMappingExposure=1.04;this.renderer.shadowMap.enabled=true;this.renderer.shadowMap.type=THREE.PCFSoftShadowMap;this.renderer.setClearColor(0x10272c);
  const pmrem=new THREE.PMREMGenerator(this.renderer);const environmentScene=new RoomEnvironment();this.environment=pmrem.fromScene(environmentScene,0.04).texture;environmentScene.dispose();pmrem.dispose();
  this.camera=new THREE.PerspectiveCamera(68,innerWidth/innerHeight,0.08,600);this.camera.rotation.order='YXZ';this.world=new World(this.environment);this.world.build('observatory',this.run);this.ray=new THREE.Raycaster();this.ray.far=3.65;this.ray.near=0;
  this.lowQuality=this.settings.quality==='low';this.applyQuality();this.bindEvents();this.syncSettings();this.refreshDiscovery();this.resize();window.__GAME__=this;
  if(this.qaMode)this.qa={enter:room=>{if(!ROOM_IDS.includes(room))throw new Error('Unknown QA room');this.state='playing';this.hideOverlays();show('hud');this.enterRoom(room);return this.snapshot();},act:action=>{const target=this.world.targets.find(t=>t.action===action);if(!target)throw new Error(`No ${action} target in ${this.run.room}`);this.useAction(action,true);return this.snapshot();},advanceQuiet:seconds=>{for(let i=0;i<Math.ceil(seconds/0.05);i++)this.update(0.05,performance.now()/1000);return this.snapshot();},pose:(x,z,yaw=0,pitch=0)=>{this.camera.position.set(x,1.7,z);this.yaw=yaw;this.pitch=pitch;this.camera.rotation.set(pitch,yaw,0);return this.snapshot();},reset:()=>this.newRun(false),grant:id=>{this.run.traces={...this.run.traces,[id]:true};this.refreshTraces();return this.snapshot();},do:action=>{this.useAction(action,true);return this.snapshot();}};
  $('begin').disabled=false;$('begin').textContent='Begin';window.addEventListener('error',e=>this.metrics.errors.push(e.message));window.addEventListener('unhandledrejection',e=>this.metrics.errors.push(String(e.reason)));
  this.lastFrame=performance.now();this.animate=this.animate.bind(this);requestAnimationFrame(this.animate);
 }
 bindEvents(){
  $('begin').onclick=()=>this.newRun();$('continue').onclick=()=>this.continueRun();$('resume').onclick=()=>this.resume();$('pause-small').onclick=()=>this.pause();$('menu-settings').onclick=()=>this.openSettings('menu');$('pause-settings').onclick=()=>this.openSettings('pause');$('settings-close').onclick=()=>this.closeSettings();
  $('main-menu').onclick=()=>this.title();$('return-room').onclick=()=>{this.resume();this.goRoom('office');};$('again').onclick=()=>this.newRun();$('ending-menu').onclick=()=>this.title();$('menu-endings').onclick=()=>{this.showCollection();};$('collection-close').onclick=()=>{show('collection',false);show('menu');};$('dossier-button').onclick=()=>{this.showDossier();};$('dossier-close').onclick=()=>{show('dossier',false);show('pause');};
  $('transcript-button').onclick=()=>{show('pause',false);show('transcript');$('transcript-lines').replaceChildren(...this.history.map(item=>{const p=document.createElement('p');p.textContent=item.text;return p;}));};$('transcript-close').onclick=()=>{show('transcript',false);show('pause');};
  $('sensitivity').oninput=e=>{this.settings.sensitivity=Number(e.target.value);$('sensitivity-value').textContent=this.settings.sensitivity.toFixed(1);this.persistSettings();};
  $('voice').onchange=e=>{this.settings.voice=e.target.checked;this.audio.voice=this.settings.voice;if(!this.settings.voice)this.audio.stopVoice();this.persistSettings();};$('muted').onchange=e=>{this.settings.muted=e.target.checked;this.audio.mute(this.settings.muted);this.persistSettings();};$('motion').onchange=e=>{this.settings.motion=e.target.checked;this.persistSettings();};$('quality').onchange=e=>{this.settings.quality=e.target.value;this.lowQuality=this.settings.quality==='low';this.applyQuality();this.persistSettings();};
  window.addEventListener('resize',()=>this.resize());document.addEventListener('pointerlockchange',()=>{const was=this.mouseCaptured;this.mouseCaptured=document.pointerLockElement===$('world');if(was&&!this.mouseCaptured&&this.state==='playing'&&!this.transitioning)this.pause();});
  $('world').addEventListener('click',()=>{if(this.state!=='playing')return;if(this.target)this.useAction(this.target.action);else this.captureMouse();});
  $('world').addEventListener('pointerdown',e=>{if(this.state==='playing'&&!this.mouseCaptured&&e.button===0){this.dragging=true;this.dragX=e.clientX;this.dragY=e.clientY;}});window.addEventListener('pointerup',()=>{this.dragging=false;});
  document.addEventListener('mousemove',e=>{if(this.state!=='playing'||this.transitioning)return;let dx=0,dy=0;if(this.mouseCaptured){dx=e.movementX;dy=e.movementY;}else if(this.dragging){dx=e.clientX-this.dragX;dy=e.clientY-this.dragY;this.dragX=e.clientX;this.dragY=e.clientY;}if(dx||dy){this.yaw-=dx*0.002*this.settings.sensitivity;this.pitch=Math.max(-1.30,Math.min(1.30,this.pitch-dy*0.002*this.settings.sensitivity));this.idleTime=0;}});
  document.addEventListener('keydown',e=>{if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Space'].includes(e.code)&&this.state==='playing')e.preventDefault();if(e.code==='Escape'){if(!$('settings').hidden)this.closeSettings();else if(!$('transcript').hidden){show('transcript',false);show('pause');}else if(!$('collection').hidden){show('collection',false);show('menu');}else if(!$('dossier').hidden){show('dossier',false);show('pause');}else if(this.state==='playing')this.pause();else if(this.state==='paused'&&!this.transitioning)this.resume(false);return;}
   if(this.state!=='playing'||this.transitioning)return;this.keys.add(e.code);this.idleTime=0;if(e.repeat)return;if(e.code==='KeyE')this.useAction(this.target?.action);if(e.code==='KeyH')document.body.classList.toggle('hud-minimal');if(e.code==='KeyV'){this.settings.voice=!this.settings.voice;this.audio.voice=this.settings.voice;this.audio.stopVoice();this.syncSettings();this.persistSettings();this.toast(this.settings.voice?'Local voice on · captions always available':'Voice off · captions still tell the story');}if(e.code==='KeyM'){this.settings.muted=!this.settings.muted;this.audio.mute(this.settings.muted);this.syncSettings();this.persistSettings();this.toast(this.settings.muted?'Sound off':'Sound on');}if(e.code==='Space'&&!this.run.seen.no_jump){this.run.seen.no_jump=true;this.say('no_jump');}
  });
  document.addEventListener('keyup',e=>this.keys.delete(e.code));window.addEventListener('blur',()=>{this.keys.clear();this.dragging=false;if(this.state==='playing')this.pause();});document.addEventListener('visibilitychange',()=>{if(document.hidden){this.keys.clear();if(this.state==='playing')this.pause();}});
 }
 hideOverlays(){overlays.forEach(id=>show(id,false));}
 persistSettings(){if(this.qaMode)return;try{localStorage.setItem('sadmans-parable:settings',JSON.stringify(this.settings));}catch{this.toast('Settings cannot be saved here. You can still play.');}}
 syncSettings(){$('sensitivity').value=this.settings.sensitivity;$('sensitivity-value').textContent=this.settings.sensitivity.toFixed(1);$('voice').checked=this.settings.voice;$('muted').checked=this.settings.muted;$('motion').checked=this.settings.motion;$('quality').value=this.settings.quality;}
 applyQuality(){this.renderer.shadowMap.enabled=!this.lowQuality;this.renderer.setPixelRatio(this.lowQuality?1:Math.min(devicePixelRatio,1.5));this.resize();}
 resize(){this.renderer.setSize(innerWidth,innerHeight,false);this.camera.aspect=innerWidth/innerHeight;this.camera.updateProjectionMatrix();}
 save(){if(this.qaMode)return;try{localStorage.setItem(SAVE_KEY,JSON.stringify(this.saved));}catch{this.toast('This browser is not saving discoveries. The game still works.');}}
 checkpoint(){if(this.state!=='playing')return;this.saved.checkpoint={room:this.run.room,run:{...this.run,sitting:false,quietTime:0}};this.save();}
 refreshDiscovery(){$('discovered').textContent=this.saved.endings.length?`${this.saved.endings.length} of ${ENDINGS_TOTAL} endings found. None of them is a grade.`:'An original first-person fable.';show('continue',!!this.saved.checkpoint);this.refreshTraces();}
 refreshTraces(){const found=traceCount(this.run);const el=$('traces');el.textContent=found?`traces ${found} / ${TRACE_IDS.length}`:'';el.hidden=!found;}
 showDossier(){const list=$('dossier-list');list.replaceChildren();const found=TRACE_IDS.filter(id=>this.run.traces[id]);if(!found.length){const p=document.createElement('p');p.textContent='Nothing yet. The building is comfortable with that.';list.append(p);}for(const id of found){const article=document.createElement('article'),h=document.createElement('h3'),p=document.createElement('p');h.textContent=TRACES[id][0];p.textContent=TRACES[id][1];article.append(h,p);list.append(article);}if(traceCount(this.run)<2){const p=document.createElement('p');p.className='fine';p.textContent='Somewhere still sealed: a place where the Building is mended.';list.append(p);}if(traceCount(this.run)<3){const p=document.createElement('p');p.className='fine';p.textContent='Somewhere still sealed: a way above the Building.';list.append(p);}show('pause',false);show('dossier');$('dossier-close').focus();}
 captureMouse(){if(this.qaMode)return;try{const promise=$('world').requestPointerLock?.();if(promise?.catch)promise.catch(()=>this.toast('Mouse capture unavailable · drag to look, or use arrow keys'));}catch{this.toast('Drag to look, or use the arrow keys.');}}
 releaseMouse(){if(document.pointerLockElement)document.exitPointerLock();this.keys.clear();this.dragging=false;}
 newRun(capture=true){this.run=initialRun();this.saved.runs++;this.history=[];this.state='playing';this.hideOverlays();show('hud');this.audio.unlock();this.enterRoom('office');this.say(this.saved.runs>1?'office_return':'office_intro');if(capture)this.captureMouse();this.refreshDiscovery();}
 continueRun(){const checkpoint=this.saved.checkpoint;if(!checkpoint){this.newRun();return;}const fresh=initialRun(),saved=checkpoint.run??{};for(const key of ['stamps','button','loops','petty','desk','books','files','shelf','listens','mercy','elapsed']){fresh[key]=Number.isFinite(saved[key])?Math.max(0,Math.min(saved[key],key==='elapsed'?86400:100)):0;}fresh.tree=!!saved.tree;fresh.authorFound=!!saved.authorFound;fresh.predecessor=!!saved.predecessor;fresh.alignment=['self','story','none'].includes(saved.alignment)?saved.alignment:null;fresh.traces=saved.traces&&typeof saved.traces==='object'?Object.fromEntries(Object.entries(saved.traces).filter(([k,v])=>TRACE_IDS.includes(k)&&v===true)):{};fresh.visits={};fresh.seen={};this.run=fresh;this.state='playing';this.hideOverlays();show('hud');this.audio.unlock();this.enterRoom(checkpoint.room);this.say(checkpoint.room+'_intro');this.captureMouse();}
 enterRoom(room){this.run.room=room;this.run.sitting=false;this.run.quietTime=0;this.run.visits={...this.run.visits,[room]:(this.run.visits[room]||0)+1};this.world.build(room,this.run);const s=this.world.spawn;this.camera.position.set(s.x,1.7,s.z);this.yaw=s.yaw;this.pitch=0;this.camera.rotation.set(0,s.yaw,0);this.keys.clear();this.target=null;this.idleTime=0;this.idleStage=0;this.stepClock=0;this.metrics.roomChanges++;this.audio.mood(room);$('room-name').textContent=ROOM_NAMES[room];show('quiet-note',false);show('interact',false);$('crosshair').classList.remove('target');this.refreshTraces();this.checkpoint();}
 goRoom(room,prior=null,immediate=false){if(this.transitioning)return;this.transitioning=true;this.keys.clear();$('fade').classList.add('active');this.audio.transition();const travel=()=>{this.enterRoom(room);this.transitioning=false;$('fade').classList.remove('active');let entry=room+'_intro';if(room==='office')entry='office_return';if(room==='hub'&&this.run.visits.hub>1)entry='hub_wait';if(room==='loop'&&this.run.visits.loop>1)entry=null;this.sayText([prior?story.lines[prior]:null,entry?story.lines[entry]:null].filter(Boolean).join(' '));};if(immediate||this.qaMode)travel();else setTimeout(travel,230);}
 useAction(action,bypass=false){if(this.state!=='playing'||this.transitioning||!action)return;const now=performance.now();if(!bypass&&now-this.lastInteract<330)return;this.lastInteract=now;this.audio.unlock();this.audio.click();this.metrics.interactions++;this.idleTime=0;const outcome=interact(this.run,action);this.run=outcome.run;this.world.refresh(this.run);if(outcome.ending){this.finish(outcome.ending,outcome.line);return;}if(outcome.room){this.goRoom(outcome.room,outcome.line);return;}if(outcome.line)this.say(outcome.line);show('quiet-note',this.run.sitting);this.refreshTraces();this.checkpoint();}
 say(id){const text=story.lines[id];if(text)this.sayText(text);}
 sayText(text){if(!text)return;const last=this.history.at(-1);if(last?.text===text)return;this.history.push({room:this.run.room,text});if(this.history.length>120)this.history.shift();$('caption').textContent=text;$('subtitle').classList.remove('empty');this.subtitleUntil=performance.now()+Math.max(6200,text.split(/\s+/).length*335);this.audio.narrate(text);}
 toast(text){$('toast').textContent=text;$('toast').classList.add('show');this.toastUntil=performance.now()+4200;}
 finish(id,prior){const ending=story.endings[id];if(!ending)throw new Error('Unknown ending '+id);this.state='ended';this.run.sitting=false;this.saved.endings=[...new Set([...this.saved.endings,id])];this.saved.last=id;this.saved.checkpoint=null;this.save();this.releaseMouse();this.hideOverlays();show('hud',false);show('ending');$('ending-title').textContent=ending.title;$('ending-text').textContent=ending.text;$('ending-after').textContent=ending.after;$('ending-count').textContent=`${this.saved.endings.length} of ${ENDINGS_TOTAL} endings discovered`;
  this.audio.stopVoice();this.audio.transition();this.audio.narrate((prior?story.lines[prior]+' ':'')+ending.text);this.refreshDiscovery();$('again').focus();}
 pause(){if(this.state!=='playing')return;this.state='paused';this.run.quietTime=0;this.releaseMouse();this.audio.stopVoice();show('pause');show('hud',false);$('performance').textContent=`${Math.round(this.fps)} fps · ${this.lowQuality?'Low detail':'High detail'} · Your discoveries are local.`;$('resume').focus();}
 resume(capture=true){if(this.state!=='paused')return;this.state='playing';this.hideOverlays();show('hud');this.audio.unlock();if(capture)this.captureMouse();}
 title(){this.state='menu';this.releaseMouse();this.audio.stopVoice();this.hideOverlays();show('hud',false);show('menu');this.world.build('observatory',this.run);this.refreshDiscovery();}
 openSettings(returnTo){this.returnTo=returnTo;if(this.state==='playing')this.pause();show(returnTo,false);show('settings');this.syncSettings();$('settings-close').focus();}
 closeSettings(){show('settings',false);show(this.returnTo||'pause');}
 showCollection(){show('menu',false);show('collection');const list=$('ending-list');list.replaceChildren();for(const id of this.saved.endings){const article=document.createElement('article'),h=document.createElement('h3'),p=document.createElement('p');h.textContent=story.endings[id].title;p.textContent=story.endings[id].text;article.append(h,p);list.append(article);}if(!this.saved.endings.length){const p=document.createElement('p');p.textContent='No endings found yet. The building would prefer you not investigate that.';list.append(p);}}
 findTarget(){this.camera.updateMatrixWorld();this.ray.setFromCamera(new THREE.Vector2(0,0),this.camera);this.world.scene.updateMatrixWorld(true);const hits=this.ray.intersectObjects(this.world.targets.map(t=>t.mesh),false);let found=null;if(hits.length){const candidate=this.world.targets.find(t=>t.mesh===hits[0].object);const occlusionRay=new THREE.Raycaster(this.camera.position,this.ray.ray.direction,0,hits[0].distance-0.06);const blockers=occlusionRay.intersectObjects(this.world.scene.children,true).filter(hit=>hit.object.visible&&hit.object.isMesh&&!hit.object.material?.transparent&&hit.distance>0.1);if(blockers.length===0)found=candidate;}
  this.target=found;show('interact',!!found);$('crosshair').classList.toggle('target',!!found);if(found)$('interact-label').textContent=found.label;}
 update(dt,time){
  this.world.update(time);if(this.state==='menu'){this.camera.position.set(8+Math.sin(time*0.06)*1.2,5.2,15);this.camera.lookAt(0,7,-5);return;}
  if(this.state!=='playing'||this.transitioning)return;
  this.run.elapsed+=dt;this.idleTime+=dt;this.audio.update(time);const action=actionsForKeys(this.keys);this.yaw-=action.turn*dt*1.55;this.camera.rotation.set(this.pitch,this.yaw,0);let forward=action.forward,right=action.right;const length=Math.hypot(forward,right);if(length>1){forward/=length;right/=length;}
  const speed=action.run?RUN_SPEED:WALK_SPEED;const dx=(-Math.sin(this.yaw)*forward+Math.cos(this.yaw)*right)*speed*dt,dz=(-Math.cos(this.yaw)*forward-Math.sin(this.yaw)*right)*speed*dt;
  const moved=moveCircle(this.camera.position,{x:dx,z:dz},this.world.bounds,this.world.colliders);const moving=Math.hypot(moved.x-this.camera.position.x,moved.z-this.camera.position.z)>0.001;
  this.camera.position.x=moved.x;this.camera.position.z=moved.z;if(moving){this.idleTime=0;if(this.run.sitting){this.run.sitting=false;this.run.quietTime=0;show('quiet-note',false);this.say('quiet_early');}this.stepClock+=dt;if(this.stepClock>(action.run?0.33:0.48)){this.stepClock=0;this.audio.step();}}
  const targetHeight=this.run.sitting?1.15:1.7;this.camera.position.y+=(targetHeight-this.camera.position.y)*(1-Math.exp(-dt*9));if(moving&&!this.settings.motion)this.camera.position.y+=Math.sin(time*(action.run?14:10))*0.012;
  if(this.run.room==='quiet'&&this.run.sitting&&!moving){this.run.quietTime+=dt;if(this.run.quietTime>=QUIET_SECONDS){this.finish('stillness','quiet_ready');return;}}
  if(this.idleTime>28&&this.idleStage===0&&!this.run.sitting){this.idleStage=1;this.say('idle1');}else if(this.idleTime>65&&this.idleStage===1&&!this.run.sitting){this.idleStage=2;this.say('idle2');}
  if(this.run.elapsed>75&&action.run&&!this.run.seen.pace_fast){this.run.seen.pace_fast=true;this.say('pace_fast');}
  this.findTarget();
 }
 animate(now){requestAnimationFrame(this.animate);const raw=(now-this.lastFrame)/1000;this.lastFrame=now;const dt=Math.min(raw,0.05);const time=now/1000;this.frameSamples.push(raw);if(this.frameSamples.length>90)this.frameSamples.shift();this.fps=1/(this.frameSamples.reduce((a,b)=>a+b,0)/this.frameSamples.length||1/60);
  if(this.settings.quality==='auto'&&this.state==='playing'&&this.metrics.frames>240&&this.fps<27&&!this.lowQuality&&!document.hidden){this.lowQuality=true;this.metrics.qualityChanges++;this.applyQuality();this.toast('Lowered rendering detail · your choices are unchanged');}
  this.update(dt,time);if(now>this.subtitleUntil)$('subtitle').classList.add('empty');if(now>this.toastUntil)$('toast').classList.remove('show');this.renderer.render(this.world.scene,this.camera);this.metrics.frames++;this.metrics.maxDraws=Math.max(this.metrics.maxDraws,this.renderer.info.render.calls);
 }
 snapshot(){return {state:this.state,room:this.run.room,position:this.camera.position.toArray(),yaw:this.yaw,pitch:this.pitch,run:JSON.parse(JSON.stringify(this.run)),endings:[...this.saved.endings],target:this.target?.action||null,traces:traceCount(this.run),alignment:this.run.alignment,predecessor:this.run.predecessor,caption:$('caption').textContent,frames:this.metrics.frames,fps:Math.round(this.fps),draws:this.renderer.info.render.calls,triangles:this.renderer.info.render.triangles,textures:this.renderer.info.memory.textures,geometries:this.renderer.info.memory.geometries,mouseCaptured:this.mouseCaptured,metrics:{...this.metrics},qaMode:this.qaMode};}
}

(async()=>{try{await document.fonts.ready;new Game();}catch(error){show('error');$('error-text').textContent=`${error.message}. Open the offline HTML in a current Chrome or Edge with hardware acceleration enabled, then try again.`;console.error(error);}})();
